### ISSUE TITLE
ValueError and unreadable results in the supplier_tester results table

### ISSUE THREAD

**Issue by blaise-io** [Tiqets/supplier-api#50]
When running the supplier tester (e.g. `supplier_tester --url=http://localhost:18021/tiqets/a05a4e76-0cb3-478b-92d8-d8cc54b3ca20 --product-id=fd62f6c7-add1-4ea0-a58a-0cd19c01c83a --api-key=secret --no-colors --availability --timeslots`), sometimes the supplier tester reports long errors.

Sometimes it tries to wrap an error message to 3 character-columns, which creates unreadable results: Example:
```
-----------------
RESERVATION TESTS
-----------------

+---+-------+------------------------------------------------+----------+-----+
| # | Time  | Test name                                      | Result   | Des |
|   |       |                                                |          | cri |
|   |       |                                                |          | pti |
|   |       |                                                |          | on  |
+---+-------+------------------------------------------------+----------+-----+
| 1 | 28ms  | Request without API-Key                        | OK       |     |
| 2 | 10ms  | Request with incorrect API-Key                 | OK       |     |
| 3 | 85ms  | Testing missing argument errors                | WARNINIG | Inc |
|   |       |                                                |          | orr |
|   |       |                                                |          | ect |
|   |       |                                                |          | mes |
|   |       |                                                |          | sag |
|   |       |                                                |          | e t |
|   |       |                                                |          | ext |
|   |       |                                                |          | "Re |
|   |       |                                                |          | qui |
|   |       |                                                |          | red |
|   |       |                                                |          | arg |
|   |       |                                                |          | ume |
|   |       |                                                |          | nt  |
|   |       |                                                |          | dat |
|   |       |                                                |          | e   |
|   |       |                                                |          | was |
|   |       |                                                |          | not |
|   |       |                                                |          | fou |
|   |       |                                                |          | nd" |
|   |       |                                                |          | . E |
|   |       |                                                |          | xpe |
|   |       |                                                |          | cte |
|   |       |                                                |          | d t |
|   |       |                                                |          | ext |
|   |       |                                                |          | sho |
|   |       |                                                |          | uld |
|   |       |                                                |          | sta |
|   |       |                                                |          | rt  |
|   |       |                                                |          | wit |
|   |       |                                                |          | h:  |
|   |       |                                                |          | "Re |
|   |       |                                                |          | qui |
|   |       |                                                |          | red |
|   |       |                                                |          | arg |
|   |       |                                                |          | ume |
|   |       |                                                |          | nt  |
|   |       |                                                |          | "da |
|   |       |                                                |          | te" |
|   |       |                                                |          | was |
|   |       |                                                |          | not |
|   |       |                                                |          | fou |
|   |       |                                                |          | nd" |
|   |       |                                                |          | Inc |
|   |       |                                                |          | orr |
|   |       |                                                |          | ect |
|   |       |                                                |          | mes |
|   |       |                                                |          | sag |
|   |       |                                                |          | e t |
|   |       |                                                |          | ext |
|   |       |                                                |          | "Re |
|   |       |                                                |          | qui |
|   |       |                                                |          | red |
|   |       |                                                |          | arg |
|   |       |                                                |          | ume |
|   |       |                                                |          | nt  |
|   |       |                                                |          | tic |
|   |       |                                                |          | ket |
|   |       |                                                |          | s   |
|   |       |                                                |          | was |
|   |       |                                                |          | not |
|   |       |                                                |          | fou |
|   |       |                                                |          | nd" |
|   |       |                                                |          | . E |
|   |       |                                                |          | xpe |
|   |       |                                                |          | cte |
|   |       |                                                |          | d t |
|   |       |                                                |          | ext |
|   |       |                                                |          | sho |
|   |       |                                                |          | uld |
|   |       |                                                |          | sta |
|   |       |                                                |          | rt  |
|   |       |                                                |          | wit |
|   |       |                                                |          | h:  |
|   |       |                                                |          | "Re |
|   |       |                                                |          | qui |
|   |       |                                                |          | red |
|   |       |                                                |          | arg |
|   |       |                                                |          | ume |
|   |       |                                                |          | nt  |
|   |       |                                                |          | "ti |
|   |       |                                                |          | cke |
|   |       |                                                |          | ts" |
|   |       |                                                |          | was |
|   |       |                                                |          | not |
|   |       |                                                |          | fou |
|   |       |                                                |          | nd" |
|   |       |                                                |          | Inc |
|   |       |                                                |          | orr |
|   |       |                                                |          | ect |
|   |       |                                                |          | mes |
|   |       |                                                |          | sag |
|   |       |                                                |          | e t |
|   |       |                                                |          | ext |
|   |       |                                                |          | "Re |
|   |       |                                                |          | qui |
|   |       |                                                |          | red |
|   |       |                                                |          | arg |
|   |       |                                                |          | ume |
|   |       |                                                |          | nt  |
|   |       |                                                |          | cus |
|   |       |                                                |          | tom |
|   |       |                                                |          | er  |
|   |       |                                                |          | was |
|   |       |                                                |          | not |
|   |       |                                                |          | fou |
|   |       |                                                |          | nd" |
|   |       |                                                |          | . E |
|   |       |                                                |          | xpe |
|   |       |                                                |          | cte |
|   |       |                                                |          | d t |
|   |       |                                                |          | ext |
|   |       |                                                |          | sho |
|   |       |                                                |          | uld |
|   |       |                                                |          | sta |
|   |       |                                                |          | rt  |
|   |       |                                                |          | wit |
|   |       |                                                |          | h:  |
|   |       |                                                |          | "Re |
|   |       |                                                |          | qui |
|   |       |                                                |          | red |
|   |       |                                                |          | arg |
|   |       |                                                |          | ume |
|   |       |                                                |          | nt  |
|   |       |                                                |          | "cu |
|   |       |                                                |          | sto |
|   |       |                                                |          | mer |
|   |       |                                                |          | "   |
|   |       |                                                |          | was |
|   |       |                                                |          | not |
|   |       |                                                |          | fou |
|   |       |                                                |          | nd" |
| 4 | 101ms | Reserving tickets for at least 1 variant       | OK       |     |
| 5 | 56ms  | Testing reservation for non-existing product   | OK       |     |
| 6 | 54ms  | Testing reservation with incorrect date format | OK       |     |
| 7 | 50ms  | Testing reservation with past date             | OK       |     |
| 8 | 88ms  | Testing methods that are not allowed           | OK       |     |
+---+-------+------------------------------------------------+----------+-----+
```

But even worse, sometimes it tries to wrap to a negative character-columns, which breaks, see log below. 

```text
Traceback (most recent call last):
  File "/Users/blaise/env/paylogic/supplier-middleware/.env/bin/supplier_tester", line 8, in <module>
    sys.exit(supplier_tester())
  File "/Users/blaise/env/paylogic/supplier-middleware/.env/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/blaise/env/paylogic/supplier-middleware/.env/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/blaise/env/paylogic/supplier-middleware/.env/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/blaise/env/paylogic/supplier-middleware/.env/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/blaise/env/paylogic/supplier-middleware/.env/lib/python3.8/site-packages/supplier_api_tester/cli.py", line 50, in supplier_tester
    results_printer(results, no_colors)
  File "/Users/blaise/env/paylogic/supplier-middleware/.env/lib/python3.8/site-packages/supplier_api_tester/printer.py", line 59, in results_printer
    column[columns_count] = '\n'.join(wrap(column[columns_count], message_size))
  File "/opt/homebrew/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/textwrap.py", line 379, in wrap
    return w.wrap(text)
  File "/opt/homebrew/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/textwrap.py", line 354, in wrap
    return self._wrap_chunks(chunks)
  File "/opt/homebrew/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/textwrap.py", line 248, in _wrap_chunks
    raise ValueError("invalid width %r (must be > 0)" % self.width)
ValueError: invalid width -8 (must be > 0)
```

As a workaround, I'm overwriting .env/lib/python3.8/site-packages/terminaltables/terminal_io.py to increase `DEFAULT_WIDTH` to 120. It defaults to 79 and does not seem to match the shell window size on either Ubuntu in Docker or macOS. 

Maybe supplier_api_tester could set an explicit width of at least 120 chars for the results table.

**Comment by mennobb** [comment]
Hi Blaise, I just wanted to let you know we've seen the message and will be looking at it soon.
Thanks for your report and your patience!

**Comment by trojkat** [comment]
@blaise-io Thanks for reporting the issue, we have confirmed that it was happening when using a tiny terminal window. In the latest version (1.6.3) we added an error message that will inform that the terminal window is too narrow.
